"use client";
import { useMemo, useState } from "react";
import { BookOpen, CheckCircle2, ChevronRight, Globe2, Mail, MapPin, Menu, Phone, Send, Sparkles, X } from "lucide-react";
const logo="/assets/trinity-logo.png",founder="/assets/founder.jpg",books="/assets/education-books.png";
const courses=[
{language:"English",level:"Beginner",title:"Everyday English",text:"Build speaking confidence through practical conversations, listening, reading and writing.",accent:"#f5a95c",icon:"EN"},
{language:"English",level:"Intermediate",title:"English 4 Skills",text:"Strengthen the four core skills for school, work and confident communication.",accent:"#e8876c",icon:"A+"},
{language:"Chinese",level:"Beginner",title:"Chinese Foundations",text:"Learn pronunciation, essential characters and useful daily Mandarin expressions.",accent:"#e65d64",icon:"中"},
{language:"Chinese",level:"Exam prep",title:"HSK Preparation",text:"Structured vocabulary, grammar and mock practice for your next HSK level.",accent:"#d74752",icon:"HSK"},
{language:"Thai",level:"Beginner",title:"Thai for Daily Life",text:"Speak naturally in everyday situations with friendly, guided practice.",accent:"#786ccf",icon:"ไทย"},
{language:"Math",level:"School support",title:"Mathematics Support",text:"Clear explanations and guided problem-solving for stronger foundations.",accent:"#47a7b8",icon:"π"}];
function Logo(){return <a href="#home" className="brand"><img src={logo} alt="Trinity Learning Club"/><span><b>TRINITY</b><small>Learning Club</small></span></a>}
export default function Home(){const[menu,setMenu]=useState(false),[filter,setFilter]=useState("All"),[selected,setSelected]=useState<(typeof courses)[0]|null>(null),[sent,setSent]=useState(false);const shown=useMemo(()=>filter==="All"?courses:courses.filter(c=>c.language===filter),[filter]);return <main>
<header className="site-header"><Logo/><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button><nav className={menu?"open":""}>{["Home","Courses","About","Contact"].map(x=><a key={x} href={`#${x.toLowerCase()}`} onClick={()=>setMenu(false)}>{x}</a>)}<a className="nav-cta" href="#courses">Explore courses</a></nav></header>
<section className="hero" id="home"><div className="hero-copy"><span className="eyebrow"><Sparkles size={16}/>Learn. Connect. Grow.</span><h1>Shape your future with <em>Trinity</em></h1><p>Friendly language and mathematics classes that help every learner build real skills, confidence, and a brighter future.</p><div className="hero-actions"><a className="button primary" href="#courses">Find your course <ChevronRight size={18}/></a><a className="button secondary" href="#about">Meet our club</a></div><div className="hero-proof"><span><b>4</b>subjects</span><span><b>Supportive</b>teachers</span><span><b>Since</b>2023</span></div></div><div className="hero-art"><div className="orbit one"/><div className="orbit two"/><div className="hero-card"><Globe2/><strong>Hello! 你好!<br/>မင်္ဂလာပါ!</strong><span>Start learning today</span></div><img src={books} alt="Education books"/></div></section>
<section className="why section-pad"><div className="section-heading"><span className="eyebrow">Why Trinity?</span><h2>Learning feels easier when you belong.</h2><p>We created Trinity to make quality education accessible, engaging, and encouraging for learners in our community.</p></div><div className="benefit-grid"><article><span>01</span><BookOpen/><h3>Practical learning</h3><p>Lessons focus on skills you can use in school, work and daily life.</p></article><article><span>02</span><Globe2/><h3>Multilingual support</h3><p>Learn in a comfortable environment that understands diverse backgrounds.</p></article><article><span>03</span><Sparkles/><h3>Confidence first</h3><p>Friendly feedback and small wins keep every learner motivated.</p></article></div></section>
<section className="courses section-pad" id="courses"><div className="section-heading light"><span className="eyebrow">Our courses</span><h2>Choose what you want to learn.</h2><p>From first steps to exam preparation, there is a supportive class for your goal.</p></div><div className="filters">{["All","English","Chinese","Thai","Math"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="course-grid">{shown.map(c=><article className="course-card" key={c.title}><div className="course-icon" style={{background:c.accent}}>{c.icon}</div><div><span className="course-meta">{c.language} · {c.level}</span><h3>{c.title}</h3><p>{c.text}</p><button onClick={()=>setSelected(c)}>Course details <ChevronRight size={16}/></button></div></article>)}</div></section>
<section className="about section-pad" id="about"><div className="about-photo"><div className="photo-frame"><img src={founder} alt="Nang Mwe Kham, founder"/></div><div className="floating-note"><b>Founder-led</b><span>Community focused education</span></div></div><div className="about-copy"><span className="eyebrow">Our story</span><h2>Built from a belief in every learner.</h2><p>Trinity Learning Club was founded by Nang Mwe Kham to create inclusive learning opportunities for young people and adults. Her work in youth empowerment and multilingual education shaped a club where learners feel seen, supported, and inspired.</p><blockquote>“Education should unlock potential—not feel out of reach.”</blockquote><a className="text-link" href="#contact">Talk with our team <ChevronRight size={17}/></a></div></section>
<section className="contact section-pad" id="contact"><div className="contact-copy"><span className="eyebrow">Contact us</span><h2>Ready to start learning?</h2><p>Tell us what you want to study and our team will help you choose the right class.</p><ul><li><MapPin/>Zay Quarter, Muse Township, Northern Shan State, Myanmar</li><li><Phone/><a href="tel:+959444026504">09 444 026 504</a> · <a href="tel:+959973812326">09 973 812 326</a></li><li><Mail/><a href="mailto:mwekham170598@gmail.com">mwekham170598@gmail.com</a></li></ul></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="success"><CheckCircle2/><h3>Message ready!</h3><p>Thank you. We’ll contact you soon about your learning goal.</p><button type="button" onClick={()=>setSent(false)}>Send another</button></div>:<><label>Your name<input required placeholder="Enter your name"/></label><label>Phone or email<input required placeholder="How can we reach you?"/></label><label>Interested course<select defaultValue=""><option value="" disabled>Select a subject</option><option>English</option><option>Chinese</option><option>Thai</option><option>Mathematics</option></select></label><label>Your message<textarea placeholder="Tell us about your learning goal" rows={4}/></label><button className="button primary" type="submit">Send inquiry <Send size={17}/></button></>}</form></section>
<footer><div><Logo/><p>Accessible, engaging education that helps every learner unlock their full potential.</p></div><div><b>Explore</b><a href="#courses">Courses</a><a href="#about">About us</a><a href="#contact">Contact</a></div><div><b>Follow</b><a target="_blank" href="https://www.facebook.com/share/1A76GL4J7m/?mibextid=wwXIfr">Facebook</a><a target="_blank" href="https://www.tiktok.com/@trinitylearningclub">TikTok</a></div><small>© 2026 Trinity Learning Club · Founded September 2023</small></footer>
{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}><X/></button><div className="course-icon" style={{background:selected.accent}}>{selected.icon}</div><span className="course-meta">{selected.language} · {selected.level}</span><h2>{selected.title}</h2><p>{selected.text}</p><ul><li><CheckCircle2/>Supportive guided lessons</li><li><CheckCircle2/>Practice-based activities</li><li><CheckCircle2/>Friendly progress feedback</li></ul><a className="button primary" href="#contact" onClick={()=>setSelected(null)}>Ask about this course</a></div></div>}
</main>}
